services:
  php:
    image: tugboatqa/php:7-apache
    default: true
    depends: mysql
    
    commands:
      init:
        - docker-php-ext-install opcache
        - a2enmod headers rewrite
        
      build:
        - sed -n 's/MAGENTO_USER/'"${MAGENTO_USER}"'/' ${TUGBOAT_ROOT}/auth.json
        - sed -n 's/MAGENTO_PASS/'"${MAGENTO_PASS}"'/' ${TUGBOAT_ROOT}/auth.json
        # - mv ${TUGBOAT_ROOT}/auth.json /root/.composer/
        
        - composer create-project --repository=https://repo.magento.com/ magento/project-community-edition magento
    
  mysql:
    image: tugboatqa/mysql:5
