services:
  php:
    image: tugboatqa/php:7.1-apache
    default: true
    depends: mysql
    
    commands:
      init:
        - docker-php-ext-install opcache
        - docker-php-ext-install bcmath
        - apt-get update && apt-get install -y zlib1g-dev libicu-dev g++
        - docker-php-ext-configure intl
        - docker-php-ext-install intl
        - apt-get install -y libxslt-dev
        - docker-php-ext-install xsl
        - apt-get install -y libzip-dev
        - pecl install zip
        - docker-php-ext-enable zip
        - apt-get install -y libxml2-dev
        - docker-php-ext-install soap
        - a2enmod headers rewrite
        
      build:
        # sed -i makes a backup file. I don't like that
        - sed -in "s/MAGENTO_USER/${MAGENTO_USER}/" ${TUGBOAT_ROOT}/auth.json
        - sed -in "s/MAGENTO_PASS/${MAGENTO_PASS}/" ${TUGBOAT_ROOT}/auth.json
        - mv ${TUGBOAT_ROOT}/auth.json /root/.composer/
        
        - composer create-project --repository=https://repo.magento.com/ magento/project-community-edition magento
        
        # Set File Permissions
        - cd ${TUGBOAT_ROOT}/magento && find var generated vendor pub/static pub/media app/etc -type f -exec chmod g+w {} \;
        - cd ${TUGBOAT_ROOT}/magento && find var generated vendor pub/static pub/media app/etc -type d -exec chmod g+ws {} \;
        - cd ${TUGBOAT_ROOT}/magento && chown -R :www-data . 
        - cd ${TUGBOAT_ROOT}/magento && chmod u+x bin/magento
        
        # Install Magento
        - ${TUGBOAT_ROOT}/bin/magento setup:install \
          \--db-host=mysql \
          \--db-name=tugboat \
          \--db-user=tugboat \
          \--db-password=tugboat \
          \--backend-frontname=admin \
          \--admin-firstname=admin \
          \--admin-lastname=admin \
          \--admin-email=root@localhost \
          \--admin-user=admin \
          \--admin-password=admin123 \
          \--language=en_US \
          \--currency=USD \
          \--timezone=America/Chicago \
          \--use-rewrites=1
          
        - ln -snf "${TUGBOAT_ROOT}/magento/magento2ee" "${DOCROOT}"
    
  mysql:
    image: tugboatqa/mysql:5
