services:
  php:
    image: tugboatqa/php:7-apache
    default: true
    depends: mysql
    
    commands:
      init:
        - docker-php-ext-install opcache
        - a2enmod headers rewrite
        
      build:
        - mv ${TUGBOAT_ROOT}/auth.json /root/.composer/
    
  mysql:
    image: tugboatqa/mysql:5
